vich_uploader:
        db_driver: orm
        metadata:
            type: attribute

        mappings:
            art:
                uri_prefix: /uploads/image/art
                upload_destination: '%kernel.project_dir%/public/uploads/image/art'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            rec:
              uri_prefix: /uploads/image/rec
              upload_destination: '%kernel.project_dir%/public/uploads/image/rec'
              namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            products:
              uri_prefix: /uploads/images/products
              upload_destination: '%kernel.project_dir%/public/uploads/images/products'
              namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
